resolver: lts-18.2
packages:
- .
extra-deps:
- composite-base-0.7.5.0
- composite-aeson-0.7.5.0
- composite-aeson-throw-0.1.0.0
- compdoc-0.3.0.0
allow-newer: true
nix:
  packages: [zlib]
  enable: false
