resolver: nightly-2020-10-30
packages:
- .
extra-deps:
- composite-aeson-throw-0.1.0.0
- compdoc-0.1.0.0
- pandoc-throw-0.1.0.0
- pandoc-2.11.0.4
- citeproc-0.1.0.3
- commonmark-0.1.0.2
- commonmark-extensions-0.2.0.1
- commonmark-pandoc-0.2.0.1
nix:
  enable: false
  pure: false
  packages: [zlib]
